language: java
jdk:
- openjdk8

services:
- docker

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - GRADLE_VERSION=5.6.2
  - BITCOIND_CONNECTOR_TAG=v0.16.0
  - BITCOINJ_TAG=0.16.6-LIB
  - LATEST_VERSION=$(git log -n 1 --pretty=format:"%h")

install:
- sudo apt-get -qq update
- sudo apt-get install -y protobuf-compiler

before_script:
- gradle -version
- gradle wrapper --gradle-version=$GRADLE_VERSION
- "./scripts/install-deps.sh"

script:
- ls -l "xyz.balzaclang.balzac" | grep -e "xyz\.balzaclang\.balzac\.lib.*-bundled\.jar"
- mvn -f xyz.balzaclang.balzac.parent/ -U clean install

after_success:
- mvn -f xyz.balzaclang.balzac.lib/ jacoco:report coveralls:report -DrepoToken=$REPO_TOKEN
- docker build -f docker/Dockerfile-slim -t balzaclang/balzac:latest -t balzaclang/balzac:${LATEST_VERSION} .
- docker build -f docker/Dockerfile-slim.arm32v7 -t balzaclang/balzac-arm32v7:latest -t balzaclang/balzac-arm32v7:${LATEST_VERSION} .
- docker build -f docker/Dockerfile-slim.arm64v8 -t balzaclang/balzac-arm64v8:latest -t balzaclang/balzac-arm64v8:${LATEST_VERSION} .

notifications:
  email:
    recipients:
    - atzeinicola@gmail.com
    on_success: change
    on_failure: always

deploy:
- provider: releases
  prerelease: true
  api_key:
    secure: kgYsvSIgfx8il30hP2cfUxVElNnjQMYzoxvfedWbxowdLjK5iMeaJV65weiYJzVDRsYH3ECwoV5eRP2HnlG1F8V07ne8Ke0HVA8WNQaQL5SdSpPfwTTKeRiHVF7a1IDEQt8hfpA8KKpLKz7zCLLZyFSNM4aHaRdYVAWomhLX6gccw9lQqd2O4jYA6nb4r9R46wuJb3d6NRc8zt/SpYm6vrDZLXspSGoN9C+TKHeCCcQ3h20BaMGCQV5k7vdLgAt4FpkN8TWCUHQCwAY1bMaFeszuasFCmJum7FieHF3cl8S+5C7FgaQJOhrMINEJLFL46Cv7cgVY8gJZbnvQ4T1E+e4nospqm14jzhkfzr/m6yBSNSVl5stENRMHEDI+zWtO9OtUpg1f3OVYtq0X+yAwS+HQkxg5dg9KsAuc3yEbjbBmPV9dBaNpfNORFNdypH5BkOKrsYCOoxM9WTOZmxTtcj2obW364xb9I2vE+hd5tZv5UHTTzzDcNPNa/oUPHlRwfnevXVGL8ITghgq+5fTcRdOVI1q/pAl3mmrzY4o2W7SYIey+CbcCHek/M4fq58sFrimTFK3izbCXD1od7QYmHJuubTiuRmw1UahiClZ8BFoyRFiiJfzhIO42G1EpXnWiYFG4FcAC/tVzHDqbOfJ/JK9i/nfdKPrD5ONmE0+uLYA=
  file_glob: true
  file: xyz.balzaclang.balzac.web/target/balzac*.war
  on:
    tags: true
    jdk: openjdk8
    repo: balzac-lang/balzac
  skip-cleanup: true
- provider: script
  script: bash scripts/docker_push.sh
  on:
    tags: true
    jdk: openjdk8
    repo: balzac-lang/balzac
